//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio_ASP.NET.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cuenta
    {
        public string Cedula { get; set; }
        [Display(Name = "Número de cuenta:")]
        public string Numero { get; set; }
        [Display(Name = "Tipo de cuenta:")]
        public string Tipo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
